service: data-validation
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  get-all:
    handler: src/index.getAll
    events:
      - http:
          path: /register
          method: get
  create:
    handler: src/index.create
    events:
      - http:
          path: /register
          method: post
